### ISSUE TITLE
GC Mechanism for Actors

### ISSUE THREAD

**Issue by richardartoul** [richardartoul/nola#14]
We should build a GC mechanism for actors. Today once an actor is activated, it remains loaded in the Server's memory effectively forever.

The simplest approach to start with is to just evict the actor's from memory once they haven't received a request in X amount of time, although we should eventually support more sophisticated strategies that look at how much memory is in use by the actors and what our budget is and tries to evict intelligently.

**Comment by richardartoul** [comment]
Make sure we call the guest SHUTDOWN function as well before evicting from memory.

**Comment by richardartoul** [comment]
TODO: Consider how timers should interact with GC. Should timers firing "pin" an actor in-memory, or should only external invocations do that?

**Comment by richardartoul** [comment]
Also consider whether we need to track outstanding timers for each actor and cancel them in the event that the actor gets GC'd

**Comment by richardartoul** [comment]
After a bit more thought, I think its clear that timers should probably not keep actors pinned in-memory, or at the very least that functionality should be configurable with a default of not keeping them pinned.

In addition, we need to reconsider how timers are currently implemented because as is they have no direct connection to the actor that created them (and can even be configured to run on other actors!). This was a convenient way to implement them, but I realize now its too unconstrained. They should only be able to schedule invocations on the actor that scheduled them and they should be linked to the activation that created them instead of being able to run invocaitons anywhere in the cluster like they do now.

**Comment by gedw99** [comment]
https://github.com/thejerf/suture Has erlang like supervision tress 

seen it used on large projects where you need to run things with other things underneath and yet manage the life cycles ..

**Comment by richardartoul** [comment]
It looks a bit heavy weight for what NOLA needs. NOLA uses a “supervision-less” strategy since all actors are virtual.

I think the most straightforward approach to start with would be to add a configuration option with a reasonable default that shuts down actors once they haven’t received an RPC for x duration.

Later on we can add something more intelligent that tries to take memory into account as well.

**Comment by richardartoul** [comment]
#53 fixes all the logic around timers to behave as described earlier in this issue, so all that is left now is to actually imlement the GCing mechanism and timers will not interfere.

**Comment by gedw99** [comment]
> It looks a bit heavy weight for what NOLA needs. NOLA uses a “supervision-less” strategy since all actors are virtual.
> 
> I think the most straightforward approach to start with would be to add a configuration option with a reasonable default that shuts down actors once they haven’t received an RPC for x duration.
> 
> Later on we can add something more intelligent that tries to take memory into account as well.

Ah makes sense. Thanks @richardartoul
