### ISSUE TITLE
Potential correctness bug when using activation cache

### ISSUE THREAD

**Issue by nerdsane** [richardartoul/nola#23]
I detected a bug using a [formal model](https://github.com/richardartoul/nola/pull/22) aimed to verify that there can never be more than one instance of the same actor activated at the same time. 

The sequence of steps that will lead to this bug:

- env1 failed to heartbeat the registry and loses ownership of the actor
- actor is activated on env2
- env1 succeeds to heartbeat after a delay
- env1 receives a request to invoke the actor and proceeds with invocation
- both env 1 and env2 now have the actor in their activation cache

In the model I corrected it by adding the following:

- during a heartbeat transaction, `if last_heartbeated_at + ttl < now`, the server version is increased (this signifies that a heartbeat came in after the previous on has expired, which means there was a time where the server was considered dead)
- during the invocation request, the invocation if rejected `if env.server_version != reference.server_version` 

After the server version check was introduced, the correctness property of the model was satisfied.

Currently the activation cache TTL default is equal to heartbeat TTL, which means the activation cache should expire at the same time a server misses a heartbeat, which prevents this bug from surfacing. However, if the cache TTL is changed to longer than the heartbeat TTL, this bug will materialize.

**Comment by richardartoul** [comment]
Closed by #24
