### ISSUE TITLE
FDB installer 

### ISSUE THREAD

**Issue by gedw99** [richardartoul/nola#42]
I noticed they have windows , Mac and Linux binaries in their releases.

An addition to the makefile to curl them to down and boot them up would be nice to get going quickly .

Use case is that I want to quickly try Nola out and want to not just use the memory model.

Also a docker that runs on fly.io might be a very easy win for adoption of users too. 
fly is multi region and so makes it very easy to show off the scale out , HA and linearizabiloty aspects of Nola and FDM.

if you want sone help just yell as I am keen to try Nola with a NATS Transport on top 

btw your docs are excellent

**Comment by richardartoul** [comment]
Hey! I will happily accept a P.R with a new makefile target that installs FDB as well as Dockerfiles :)

**Comment by richardartoul** [comment]
Btw there is an open PR to support a SQL-backed store which should also make testing easier eventually (can use an RDS or fly.IO Postgres instance): https://github.com/richardartoul/nola/pull/36

**Comment by gedw99** [comment]
> Hey! I will happily accept a P.R with a new makefile target that installs FDB as well as Dockerfiles :)

WIsh i had time, but in a crush right now..

**Comment by richardartoul** [comment]
No problem. If you end up experimenting with NOLA or using it for anything let me know, whatever you’re working on sounds interesting.

If you run into any real problems also please file an issue.

**Comment by gedw99** [comment]
> 

wow interest.. Will def have a play

**Comment by richardartoul** [comment]
@gedw99 I forgot to mention, did you know there is a DNS-backed registry for NOLA? It's a lot less featureful obviously (not necessarily linearizable, no KV store, etc), but you can use it for basic actor activation/routing/discovery etc

**Comment by gedw99** [comment]
did not know that..    Got a link to its usage ?

**Comment by richardartoul** [comment]
I actually dont have an example coded up outside of `environment_test.go`. I'll try and whip one up and throw it in the examples folder.

**Comment by richardartoul** [comment]
#47 

https://github.com/richardartoul/nola/tree/master/examples/dnsregistry

That should do it, let me know if you run into any issues

**Comment by gedw99** [comment]
I will try it . Am swamped right now though so will be a while

**Comment by gedw99** [comment]
thanks works great !
